//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGiaiDau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatchDetail
    {
        public int MatchDetailID { get; set; }
        public Nullable<int> MatchID { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public string Action { get; set; }
        public Nullable<int> ActionMinute { get; set; }
    
        public virtual Match Match { get; set; }
        public virtual Player Player { get; set; }
    }
}
