//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGiaiDau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamTournament
    {
        public int TeamTournamentID { get; set; }
        public Nullable<int> TeamID { get; set; }
        public Nullable<int> TournamentID { get; set; }
    
        public virtual Team Team { get; set; }
        public virtual Tournament Tournament { get; set; }
    }
}
